use super::definition::UnitDefinition;
use super::definition_id::UnitDefinitionId;
use super::render_key::UnitRenderKey;

/// Minimal starter unit catalog when Excel import is unavailable (ADR-027 U1).
pub fn starter_definitions() -> Vec<UnitDefinition> {
    vec![
        UnitDefinition::new(
            UnitDefinitionId::new("wolf"),
            "Wolf",
            "Wild",
            2,
            5,
            4,
            6,
            3,
            7,
            2,
            3,
            26.5,
            "Elite",
            4.5,
            0.6,
            40.0,
            true,
            UnitRenderKey::reserved("wolf"),
        ),
        UnitDefinition::new(
            UnitDefinitionId::new("bandit"),
            "Bandit Scout",
            "Bandits",
            3,
            8,
            4,
            7,
            3,
            6,
            3,
            4,
            31.6,
            "Elite",
            3.8,
            0.45,
            35.0,
            true,
            UnitRenderKey::reserved("bandit"),
        ),
        UnitDefinition::new(
            UnitDefinitionId::new("deer"),
            "Deer",
            "Wild",
            1,
            4,
            2,
            5,
            2,
            8,
            1,
            2,
            12.0,
            "Common",
            5.5,
            0.5,
            30.0,
            true,
            UnitRenderKey::reserved("deer"),
        ),
    ]
}
