use crate::world::{ItemCategoryId, ItemDefinition, ItemDefinitionId, ItemIconKey};

/// Starter item definitions for tests and dev fallback (ADR-087 I1).
pub fn starter_definitions() -> Vec<ItemDefinition> {
    vec![
        ItemDefinition::new(
            ItemDefinitionId::new("gold"),
            "Gold",
            "Physical gold coins carried as stackable currency.",
            ItemCategoryId::new("currency"),
            1,
            1,
            true,
            999,
            1,
            1,
            true,
        )
        .with_icon_key(ItemIconKey::reserved("gold")),
        ItemDefinition::new(
            ItemDefinitionId::new("iron_ore"),
            "Iron Ore",
            "Raw iron ore for smelting.",
            ItemCategoryId::new("raw_material"),
            2,
            2,
            true,
            50,
            2_000,
            2,
            true,
        ),
        ItemDefinition::new(
            ItemDefinitionId::new("stone"),
            "Stone",
            "Quarried stone for construction.",
            ItemCategoryId::new("raw_material"),
            2,
            2,
            true,
            50,
            2_500,
            2,
            true,
        ),
        ItemDefinition::new(
            ItemDefinitionId::new("coal"),
            "Coal",
            "Fuel for smelting and baking.",
            ItemCategoryId::new("raw_material"),
            2,
            2,
            true,
            50,
            1_000,
            2,
            true,
        ),
        ItemDefinition::new(
            ItemDefinitionId::new("iron_bar"),
            "Iron Bar",
            "Refined iron ready for crafting.",
            ItemCategoryId::new("component"),
            2,
            2,
            true,
            50,
            1_500,
            2,
            true,
        ),
        ItemDefinition::new(
            ItemDefinitionId::new("slag"),
            "Slag",
            "Waste from smelting.",
            ItemCategoryId::new("miscellaneous"),
            2,
            2,
            true,
            50,
            500,
            2,
            true,
        ),
        ItemDefinition::new(
            ItemDefinitionId::new("flour"),
            "Flour",
            "Milled grain for baking.",
            ItemCategoryId::new("raw_material"),
            2,
            2,
            true,
            50,
            500,
            2,
            true,
        ),
        ItemDefinition::new(
            ItemDefinitionId::new("water"),
            "Water",
            "Clean water for recipes.",
            ItemCategoryId::new("raw_material"),
            1,
            1,
            true,
            50,
            200,
            1,
            true,
        ),
        ItemDefinition::new(
            ItemDefinitionId::new("fuel"),
            "Fuel",
            "Combustible fuel for ovens.",
            ItemCategoryId::new("raw_material"),
            2,
            2,
            true,
            50,
            800,
            2,
            true,
        ),
        ItemDefinition::new(
            ItemDefinitionId::new("bread"),
            "Bread",
            "Fresh baked bread.",
            ItemCategoryId::new("food"),
            2,
            2,
            true,
            20,
            300,
            2,
            true,
        ),
        ItemDefinition::new(
            ItemDefinitionId::new("healing_kit"),
            "Healing Kit",
            "Medical supplies.",
            ItemCategoryId::new("medicine"),
            2,
            2,
            false,
            1,
            300,
            25,
            true,
        )
        .with_unique_instance_required(true),
    ]
}
