use super::definition::DoodadDefinition;
use super::definition_id::DoodadDefinitionId;
use super::render_key::DoodadRenderKey;
use crate::world::DoodadKind;

/// Starter catalog content for Phase 3B (ADR-016).
pub fn starter_definitions() -> Vec<DoodadDefinition> {
    vec![
        DoodadDefinition::new(
            DoodadDefinitionId::new("tree_oak"),
            DoodadKind::Tree,
            "Oak Tree",
            4.0,
            0.85,
            1.15,
            None,
            None,
            Some(25.0),
            true,
            DoodadRenderKey::reserved("tree/oak"),
        ),
        DoodadDefinition::new(
            DoodadDefinitionId::new("tree_dead"),
            DoodadKind::Tree,
            "Dead Tree",
            3.5,
            0.9,
            1.1,
            None,
            None,
            Some(30.0),
            true,
            DoodadRenderKey::reserved("tree/dead"),
        ),
        DoodadDefinition::new(
            DoodadDefinitionId::new("rock_small"),
            DoodadKind::Rock,
            "Small Rock",
            2.0,
            0.8,
            1.2,
            None,
            None,
            Some(45.0),
            true,
            DoodadRenderKey::reserved("rock/small"),
        ),
        DoodadDefinition::new(
            DoodadDefinitionId::new("rock_large"),
            DoodadKind::Rock,
            "Large Rock",
            5.0,
            0.9,
            1.1,
            None,
            None,
            Some(35.0),
            true,
            DoodadRenderKey::reserved("rock/large"),
        ),
        DoodadDefinition::new(
            DoodadDefinitionId::new("bush_scrub"),
            DoodadKind::Bush,
            "Scrub Bush",
            1.5,
            0.75,
            1.25,
            None,
            None,
            Some(30.0),
            true,
            DoodadRenderKey::reserved("bush/scrub"),
        ),
        DoodadDefinition::new(
            DoodadDefinitionId::new("ruin_stone"),
            DoodadKind::Ruin,
            "Stone Ruin",
            8.0,
            1.0,
            1.0,
            None,
            None,
            Some(15.0),
            true,
            DoodadRenderKey::reserved("ruin/stone"),
        ),
        DoodadDefinition::new(
            DoodadDefinitionId::new("resource_node_iron"),
            DoodadKind::ResourceNode,
            "Iron Node",
            3.0,
            1.0,
            1.0,
            None,
            None,
            Some(40.0),
            true,
            DoodadRenderKey::reserved("resource/iron"),
        ),
    ]
}
