use super::assignment::ensure_building_task;
use super::eligibility::building_is_constructible;
use super::types::{TaskPriority, TaskType};
use crate::world::{BuildingCatalog, BuildingId, WorldData};

/// Ensure construction tasks exist for incomplete buildings (ADR-085 B8).
pub fn sync_construction_tasks(
    world: &mut WorldData,
    building_catalog: &BuildingCatalog,
    simulation_tick: u64,
) {
    let building_ids = world.sorted_building_ids();
    for building_id in building_ids {
        let Some(record) = world.get_building(building_id) else {
            continue;
        };
        if !building_is_constructible(record) {
            continue;
        }
        let _ = ensure_building_task(
            world,
            building_id,
            TaskType::ConstructBuilding,
            TaskPriority::Normal,
            simulation_tick,
        );
        let _ = building_catalog;
    }
}

/// Remove tasks for buildings that no longer need them.
pub fn prune_invalid_building_tasks(world: &mut WorldData) {
    let task_ids = world.task_store().sorted_task_ids();
    for task_id in task_ids {
        let Some(task) = world.task_store().get(task_id).cloned() else {
            continue;
        };
        let building_id = match task.target {
            super::types::TaskTarget::Building(id) => id,
            super::types::TaskTarget::InteractionPoint { building_id, .. } => building_id,
            super::types::TaskTarget::HaulRequest {
                owning_building_id, ..
            } => owning_building_id,
        };
        let should_remove = match task.task_type {
            TaskType::Haul => world
                .get_building(building_id)
                .is_none()
                || task
                    .hauling_request_id()
                    .and_then(|id| world.hauling_request_store().get(id))
                    .is_none_or(|request| {
                        !request.status.is_open()
                    }),
            _ => world
                .get_building(building_id)
                .is_none_or(|record| match task.task_type {
                    TaskType::ConstructBuilding => !building_is_constructible(record),
                    TaskType::OperateWorkstation => {
                        !super::eligibility::building_accepts_workstation_use(record)
                    }
                    TaskType::Haul => false,
                    // Strategic tasks are regenerated by SA6; prune only if building vanished.
                    TaskType::StrategicConstruct
                    | TaskType::RepairBuilding
                    | TaskType::ClearRubble
                    | TaskType::RecruitWorker
                    | TaskType::ExpandStorage => false,
                }),
        };
        if should_remove {
            if let Some(unit_id) = task.assigned_unit_id {
                world.task_store_mut().clear_unit_assignment(unit_id);
            }
            world.task_store_mut().remove_task(task_id);
        }
    }
}
