#!/usr/bin/env python3
"""Regenerate the Hotkeys sheet in Chasma Design.xlsx from the curated inventory below.

Run after any keyboard binding change:
    python tools/update_hotkeys_sheet.py

Source of truth for bindings: Rust handlers (grep KeyCode:: in src/).
This script is the design-doc mirror — update ROWS when code changes.
"""

from __future__ import annotations

from pathlib import Path

import openpyxl
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

WORKBOOK = Path(__file__).resolve().parents[1] / "Chasma Design.xlsx"
SHEET_NAME = "Hotkeys"

# Columns: Category, Subcategory, Key, Modifiers, Action, Context / Preconditions,
#          Blocked When, Source File, Overlap Notes
ROWS: list[tuple[str, ...]] = [
    # --- GLOBAL ---
    (
        "Global",
        "Simulation",
        "Space",
        "",
        "Toggle simulation pause / resume",
        "Always (when not typing in focused text field elsewhere)",
        "Dev text focus does not block this system directly",
        "src/simulation/input.rs",
        "Shares Space with build-mode search typing only when that field focused",
    ),
    (
        "Global",
        "Simulation",
        "Shift+Space",
        "Shift",
        "Step simulation one tick",
        "Simulation control active",
        "",
        "src/simulation/input.rs",
        "",
    ),
    (
        "Global",
        "Dev Mode",
        "F12",
        "",
        "Toggle Dev Mode on/off",
        "Always",
        "",
        "src/dev/input.rs",
        "",
    ),
    # --- CAMERA ---
    (
        "Camera",
        "Pan",
        "W / A / S / D",
        "Hold",
        "Pan camera (relative to yaw)",
        "Always unless dev gate blocks camera input",
        "Dev gizmo drag may block camera",
        "src/camera/control.rs",
        "W reserved — no dev hotkey on W",
    ),
    (
        "Camera",
        "Pan",
        "Shift",
        "Shift (hold with WASD)",
        "Fast pan",
        "While panning",
        "",
        "src/camera/control.rs",
        "Also used as modifier elsewhere",
    ),
    (
        "Camera",
        "Rotate",
        "Middle mouse drag",
        "Mouse",
        "Orbit camera yaw/pitch",
        "Always unless blocked",
        "",
        "src/camera/control.rs",
        "",
    ),
    (
        "Camera",
        "Zoom",
        "Mouse wheel",
        "Mouse",
        "Zoom in/out",
        "Always unless blocked",
        "",
        "src/camera/control.rs",
        "",
    ),
    # --- GAMEPLAY ---
    (
        "Gameplay",
        "Selection",
        "Left click",
        "Mouse",
        "Select unit / clear selection on terrain",
        "Not over UI; not box-dragging",
        "Dev panel hover, build mode, inventory open",
        "src/client/pipeline.rs",
        "",
    ),
    (
        "Gameplay",
        "Selection",
        "Shift+Left click",
        "Shift",
        "Toggle unit in selection",
        "Same as left click path",
        "",
        "src/client/pipeline.rs",
        "",
    ),
    (
        "Gameplay",
        "Selection",
        "Left drag (box)",
        "Mouse",
        "Box select units",
        "Drag threshold exceeded",
        "",
        "src/client/pipeline.rs",
        "",
    ),
    (
        "Gameplay",
        "Selection",
        "Shift+Box select",
        "Shift",
        "Add units to selection",
        "Box drag",
        "",
        "src/client/pipeline.rs",
        "",
    ),
    (
        "Gameplay",
        "Selection",
        "Alt+Left click",
        "Alt",
        "Inspect unit (dev snapshot) without requiring F12",
        "Unit under cursor",
        "",
        "src/dev/inspector/input.rs",
        "Dev path; works outside dev mode for units",
    ),
    (
        "Gameplay",
        "Commands",
        "Right click",
        "Mouse",
        "Contextual command (move, attack, interact, etc.)",
        "Units selected; not over UI",
        "Build mode ghost, dev placement",
        "src/client/pipeline.rs",
        "",
    ),
    (
        "Gameplay",
        "Build Mode",
        "B",
        "",
        "Enter / exit build mode",
        "Not in build catalog search focus",
        "Build search focused",
        "src/ui/gameplay/build_mode/input.rs",
        "B also used in Dev treasury harness (World Tools tab)",
    ),
    (
        "Gameplay",
        "Build Mode",
        "Esc",
        "",
        "Cancel build placement",
        "Build mode active",
        "",
        "src/ui/gameplay/build_mode/input.rs",
        "Esc shared globally",
    ),
    (
        "Gameplay",
        "Build Mode",
        "R",
        "",
        "Rotate build ghost",
        "Ghost placing",
        "",
        "src/ui/gameplay/build_mode/input.rs",
        "R heavily reused in dev contexts",
    ),
    (
        "Gameplay",
        "Build Mode",
        "Right click",
        "Mouse",
        "Cancel build placement",
        "Build mode active",
        "",
        "src/ui/gameplay/build_mode/input.rs",
        "",
    ),
    (
        "Gameplay",
        "Build Mode",
        "Left click",
        "Mouse",
        "Place building at ghost",
        "Ghost placing; valid terrain",
        "",
        "src/ui/gameplay/build_mode/input.rs",
        "",
    ),
    (
        "Gameplay",
        "Inventory",
        "I",
        "",
        "Open primary unit inventory panel",
        "Primary unit selected",
        "",
        "src/ui/gameplay/inventory/input.rs",
        "I reused in Dev Items tab and building inspector",
    ),
    (
        "Gameplay",
        "Inventory",
        "Esc",
        "",
        "Close inventory / cancel drag / cancel split dialog",
        "Inventory UI open",
        "",
        "src/ui/gameplay/inventory/input.rs",
        "",
    ),
    (
        "Gameplay",
        "Inventory",
        "Ctrl+Click entry",
        "Ctrl",
        "Transfer one item to other pane",
        "Inventory open; dual pane",
        "",
        "src/ui/gameplay/inventory/panel.rs",
        "",
    ),
    (
        "Gameplay",
        "Inventory",
        "Shift+Click entry",
        "Shift",
        "Transfer half stack to other pane",
        "Inventory open; dual pane",
        "",
        "src/ui/gameplay/inventory/panel.rs",
        "",
    ),
    (
        "Gameplay",
        "Terrain Analysis",
        "O",
        "",
        "Toggle Terrain Analysis panel",
        "Always",
        "",
        "src/ui/gameplay/terrain_analysis/mod.rs",
        "O reused in dev (door open, auto-sort, etc.) — different contexts",
    ),
    (
        "Gameplay",
        "Terrain Analysis",
        "[",
        "",
        "Decrease overlay opacity",
        "Terrain Analysis panel open",
        "",
        "src/ui/gameplay/terrain_analysis/mod.rs",
        "[ reused in dev for floor/yaw/quantity",
    ),
    (
        "Gameplay",
        "Terrain Analysis",
        "]",
        "",
        "Increase overlay opacity",
        "Terrain Analysis panel open",
        "",
        "src/ui/gameplay/terrain_analysis/mod.rs",
        "] reused in dev contexts",
    ),
    (
        "Gameplay",
        "Commands HUD",
        "(mouse)",
        "Mouse",
        "Arm Move / Attack / Interact; Stop immediate",
        "Command panel buttons",
        "",
        "src/ui/gameplay/command_panel.rs",
        "No letter hotkeys for command palette",
    ),
    # --- DEV MODE CORE ---
    (
        "Dev Mode",
        "Core",
        "Ctrl+F",
        "Ctrl",
        "Focus catalog search or scene name field",
        "Dev mode on",
        "",
        "src/dev/input.rs",
        "",
    ),
    (
        "Dev Mode",
        "Core",
        "Tab",
        "",
        "Cycle dev panel tabs",
        "Dev mode on; no text focus",
        "Text focus",
        "src/dev/input.rs",
        "Tab reused in blueprint variant draft",
    ),
    (
        "Dev Mode",
        "Core",
        "E",
        "",
        "Toggle catalog enabled-only filter",
        "Dev mode on; no text focus; no transform target selected",
        "Text focus; gizmo transform target active",
        "src/dev/input.rs",
        "E also blueprint edit enter — building selected",
    ),
    (
        "Dev Mode",
        "Core",
        "T",
        "",
        "Cycle spawn team (Player ↔ Wilds)",
        "Dev mode on; no text focus; not Items manage subtab",
        "Text focus; Items manage subtab",
        "src/dev/input.rs",
        "T reused Items manage endpoint cycle",
    ),
    (
        "Dev Mode",
        "Core",
        "F",
        "",
        "Toggle favorite on selected catalog definition",
        "Dev mode on; no text focus",
        "Text focus (except F in search toggles favorite)",
        "src/dev/input.rs",
        "F reused in many dev harnesses",
    ),
    (
        "Dev Mode",
        "Core",
        "1–9",
        "",
        "Recall favorite catalog slot",
        "Dev mode on; no text focus",
        "Text focus",
        "src/dev/input.rs",
        "1–9 reused blueprint diagnostics/tools",
    ),
    (
        "Dev Mode",
        "Core",
        "Ctrl+1–9",
        "Ctrl",
        "Assign favorite catalog slot",
        "Dev mode on; no text focus",
        "Text focus",
        "src/dev/input.rs",
        "",
    ),
    (
        "Dev Mode",
        "Core",
        "Esc",
        "",
        "Clear text focus; cancel placement tool",
        "Dev mode on",
        "",
        "src/dev/input.rs",
        "Shared with gameplay/build/gizmo/blueprint",
    ),
    (
        "Dev Mode",
        "Core",
        "Enter",
        "",
        "Exit dev text focus (search, scene name, qty)",
        "Text field focused",
        "",
        "src/dev/input.rs",
        "",
    ),
    (
        "Dev Mode",
        "Placement",
        "Left click",
        "Mouse",
        "Spawn at terrain / place dev object",
        "Definition selected; not over panel",
        "Panel hovered",
        "src/dev/input.rs",
        "",
    ),
    (
        "Dev Mode",
        "Placement",
        "Shift+Left click",
        "Shift",
        "Larger batch spawn count",
        "Placement active",
        "",
        "src/dev/input.rs",
        "",
    ),
    (
        "Dev Mode",
        "Placement",
        "Ctrl+Left click",
        "Ctrl",
        "Repeat last spawn",
        "Placement active",
        "",
        "src/dev/input.rs",
        "",
    ),
    (
        "Dev Mode",
        "Placement",
        "Right click",
        "Mouse",
        "Cancel placement tool",
        "Placement armed; not over panel",
        "",
        "src/dev/input.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector Pick",
        "Left click",
        "Mouse",
        "Select unit / doodad / building / pile for inspection",
        "Dev mode or Alt; not gizmo dragging",
        "Panel hovered; blueprint edit active",
        "src/dev/inspector/input.rs",
        "",
    ),
    # --- DEV GIZMO ---
    (
        "Dev Mode",
        "Transform Gizmo",
        ",",
        "",
        "Translate gizmo mode",
        "Doodad or building selected; dev on; no text focus",
        "Text focus",
        "src/dev/gizmo/input.rs",
        ", also toggles building production enable",
    ),
    (
        "Dev Mode",
        "Transform Gizmo",
        ".",
        "",
        "Rotate gizmo mode",
        "Transform target selected",
        "Text focus",
        "src/dev/gizmo/input.rs",
        ". also toggles building production pause",
    ),
    (
        "Dev Mode",
        "Transform Gizmo",
        "/",
        "",
        "Scale gizmo mode",
        "Transform target selected",
        "Text focus",
        "src/dev/gizmo/input.rs",
        "Scale only — not catalog search or repeat mode",
    ),
    (
        "Dev Mode",
        "Transform Gizmo",
        "L",
        "",
        "Toggle world/local coordinate space",
        "Gizmo dragging",
        "",
        "src/dev/gizmo/input.rs",
        "L reused building door lock",
    ),
    (
        "Dev Mode",
        "Transform Gizmo",
        "X / Y / Z",
        "",
        "Axis constraint while dragging",
        "Gizmo drag active",
        "",
        "src/dev/gizmo/input.rs",
        "X also building destroy in inspector",
    ),
    (
        "Dev Mode",
        "Transform Gizmo",
        "Esc",
        "",
        "Cancel gizmo drag or exit transform mode",
        "Gizmo active",
        "",
        "src/dev/gizmo/input.rs",
        "",
    ),
    (
        "Dev Mode",
        "Transform Gizmo",
        "G (hold)",
        "Hold",
        "Follow ground on commit",
        "Committing transform",
        "",
        "src/dev/gizmo/commit.rs",
        "G reused many dev actions",
    ),
    (
        "Dev Mode",
        "Transform Gizmo",
        "O (hold)",
        "Hold",
        "Allow overlap on commit",
        "Committing doodad/building transform",
        "",
        "src/dev/gizmo/commit.rs",
        "",
    ),
    (
        "Dev Mode",
        "Transform Gizmo",
        "C (hold)",
        "Hold",
        "Cancel building task dependencies on commit",
        "Building gizmo commit",
        "",
        "src/dev/gizmo/commit.rs",
        "",
    ),
    # --- DEV DOODAD INSPECTOR ---
    (
        "Dev Mode",
        "Inspector — Doodad",
        "Arrow keys",
        "",
        "Move doodad X/Z",
        "Doodad selected; dev inspector shortcuts",
        "Text focus",
        "src/dev/inspector/doodad_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Doodad",
        "Page Up / Down",
        "",
        "Move doodad Y",
        "Doodad selected",
        "",
        "src/dev/inspector/doodad_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Doodad",
        "[ / ]",
        "",
        "Adjust doodad yaw ±5°",
        "Doodad selected",
        "",
        "src/dev/inspector/doodad_actions.rs",
        "Bracket keys reused elsewhere",
    ),
    (
        "Dev Mode",
        "Inspector — Doodad",
        "G (hold)",
        "Hold",
        "Follow ground on transform",
        "While applying doodad edit",
        "",
        "src/dev/inspector/doodad_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Doodad",
        "O (hold)",
        "Hold",
        "Allow overlapping occupancy",
        "While applying doodad edit",
        "",
        "src/dev/inspector/doodad_actions.rs",
        "",
    ),
    # --- DEV BUILDING INSPECTOR ---
    (
        "Dev Mode",
        "Inspector — Building",
        "D",
        "",
        "Damage building (−50)",
        "Building selected; dev inspector actions",
        "Text focus",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "H",
        "",
        "Heal building (+50)",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "H reused Items subtab",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "X",
        "",
        "Destroy building",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "R",
        "",
        "Set building to ruins",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "Conflicts with build-mode rotate when both active",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "C",
        "",
        "Complete building (lifecycle)",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "P",
        "",
        "Add 10% construction progress",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "P reused Items profiles subtab",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "Shift+P",
        "Shift",
        "Force settlement production replan",
        "Building linked to settlement",
        "",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "O",
        "",
        "Open first building door",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "L",
        "",
        "Lock first building door",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "I",
        "",
        "Log building inventory summary",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "Conflicts with gameplay inventory I",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "G",
        "",
        "Add 5 gold to building inventory",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "T",
        "",
        "Transfer item between selected unit and building",
        "Unit + building with inventories",
        "",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "U",
        "",
        "Toggle building container locked",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "V",
        "",
        "Validate building inventory links",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "F",
        "",
        "Refresh building terrain assessment",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        ",",
        "",
        "Toggle production enabled",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "Conflicts with gizmo translate",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        ".",
        "",
        "Toggle production paused",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "Conflicts with gizmo rotate",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "]",
        "",
        "Reset production progress",
        "Building selected; blueprint inspection inactive",
        "",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "`",
        "",
        "Toggle production advanced panel",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "\\",
        "",
        "Validate production runtime",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "'",
        "",
        "Cycle production operation (forward)",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        ";",
        "",
        "Cycle production operation (backward)",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "M",
        "",
        "Force-execute one production cycle",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "K",
        "",
        "Clear binding inventories",
        "Building selected",
        "",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "Q",
        "",
        "Spawn manual haul / cancel hauls / force-complete (modifiers)",
        "Building selected; Shift=cancel open; Ctrl=force complete",
        "",
        "src/dev/inspector/building_actions.rs",
        "",
    ),
    (
        "Dev Mode",
        "Inspector — Building",
        "(UI button)",
        "Mouse",
        "Cycle production repeat mode",
        "Building selected; Inspector tab",
        "",
        "src/dev/inspector/building_actions.rs",
        "Formerly / — now UI only",
    ),
    # --- BLUEPRINT ---
    (
        "Dev Mode",
        "Blueprint Inspection",
        "N",
        "",
        "Enter blueprint inspection mode",
        "Building selected; not already inspecting",
        "",
        "src/dev/inspector/blueprint_inspection.rs",
        "",
    ),
    (
        "Dev Mode",
        "Blueprint Inspection",
        "Esc",
        "",
        "Exit blueprint inspection",
        "Inspection active; not editing",
        "",
        "src/dev/inspector/blueprint_inspection.rs",
        "",
    ),
    (
        "Dev Mode",
        "Blueprint Inspection",
        "[ / ]",
        "",
        "Previous / next floor",
        "Inspection active",
        "",
        "src/dev/inspector/blueprint_inspection.rs",
        "",
    ),
    (
        "Dev Mode",
        "Blueprint Inspection",
        "Shift+R",
        "Shift",
        "Regenerate blueprint from mesh",
        "Inspection active",
        "",
        "src/dev/inspector/blueprint_inspection.rs",
        "",
    ),
    (
        "Dev Mode",
        "Blueprint Inspection",
        "1–9",
        "",
        "Focus validation diagnostic N",
        "Inspection active",
        "",
        "src/dev/inspector/blueprint_inspection.rs",
        "Conflicts with dev favorites when unfocused",
    ),
    (
        "Dev Mode",
        "Blueprint Inspection",
        "Enter / Esc",
        "",
        "Confirm / cancel pending blueprint action",
        "Pending confirmation dialog",
        "",
        "src/dev/inspector/blueprint_inspection.rs",
        "",
    ),
    (
        "Dev Mode",
        "Blueprint Edit",
        "E",
        "",
        "Enter blueprint edit mode",
        "Building selected; not editing",
        "",
        "src/dev/inspector/blueprint_edit.rs",
        "Conflicts with dev enabled-only filter",
    ),
    (
        "Dev Mode",
        "Blueprint Edit",
        "Ctrl+S",
        "Ctrl",
        "Save instance blueprint override",
        "Edit mode",
        "",
        "src/dev/inspector/blueprint_edit.rs",
        "",
    ),
    (
        "Dev Mode",
        "Blueprint Edit",
        "Ctrl+Shift+S",
        "Ctrl+Shift",
        "Apply blueprint to asset default",
        "Edit mode",
        "",
        "src/dev/inspector/blueprint_edit.rs",
        "",
    ),
    (
        "Dev Mode",
        "Blueprint Edit",
        "Ctrl+Shift+V",
        "Ctrl+Shift",
        "Save as new building variant",
        "Edit mode",
        "",
        "src/dev/inspector/blueprint_edit.rs",
        "",
    ),
    (
        "Dev Mode",
        "Blueprint Edit",
        "Ctrl+Alt+R",
        "Ctrl+Alt",
        "Reset instance to asset/generated",
        "Edit mode",
        "",
        "src/dev/inspector/blueprint_edit.rs",
        "",
    ),
    (
        "Dev Mode",
        "Blueprint Edit",
        "1 / 2 / 3",
        "",
        "Edit tool: select / add vertex / add entrance",
        "Edit mode",
        "",
        "src/dev/inspector/blueprint_edit.rs",
        "",
    ),
    (
        "Dev Mode",
        "Blueprint Edit",
        "Del / Backspace",
        "",
        "Delete selected blueprint element",
        "Edit mode",
        "",
        "src/dev/inspector/blueprint_edit.rs",
        "",
    ),
    (
        "Dev Mode",
        "Blueprint Edit",
        "+ / -",
        "",
        "Adjust entrance/transition radius",
        "Edit mode; element selected",
        "",
        "src/dev/inspector/blueprint_edit.rs",
        "",
    ),
    # --- DEV ITEMS ---
    (
        "Dev Mode",
        "Items Tab",
        "I",
        "",
        "Switch to Items subtab",
        "Items tab; dev on",
        "Text focus",
        "src/dev/inventory_tools/input.rs",
        "",
    ),
    (
        "Dev Mode",
        "Items Tab",
        "P",
        "",
        "Switch to Inventory Profiles subtab",
        "Items tab",
        "",
        "src/dev/inventory_tools/input.rs",
        "",
    ),
    (
        "Dev Mode",
        "Items Tab",
        "H",
        "",
        "Switch to Inventory Manage subtab",
        "Items tab",
        "",
        "src/dev/inventory_tools/input.rs",
        "",
    ),
    (
        "Dev Mode",
        "Items — Manage",
        "[ / ]",
        "",
        "Divide / multiply quantity by 10",
        "Manage subtab",
        "",
        "src/dev/inventory_tools/input.rs",
        "",
    ),
    (
        "Dev Mode",
        "Items — Manage",
        "+ / -",
        "",
        "Increment / decrement quantity",
        "Manage subtab",
        "",
        "src/dev/inventory_tools/input.rs",
        "",
    ),
    (
        "Dev Mode",
        "Items — Manage",
        "T",
        "",
        "Cycle inventory endpoint",
        "Manage subtab",
        "",
        "src/dev/inventory_tools/input.rs",
        "Overrides spawn team T",
    ),
    (
        "Dev Mode",
        "Items — Manage",
        "Y",
        "",
        "Cycle entry within endpoint",
        "Manage subtab",
        "",
        "src/dev/inventory_tools/input.rs",
        "",
    ),
    (
        "Dev Mode",
        "Items — Manage",
        "A / R / S / C / F / G / V",
        "",
        "Add / remove / set qty / clear / fill / arm pile / validate",
        "Manage subtab; target selected in inspector",
        "",
        "src/dev/inventory_tools/input.rs",
        "Letter keys reused across dev — context gated",
    ),
    (
        "Dev Mode",
        "Items — Harness",
        "N",
        "",
        "New detached inventory",
        "Items tab → Inventory Harness subtab",
        "",
        "src/dev/inventory_harness.rs",
        "",
    ),
    (
        "Dev Mode",
        "Items — Harness",
        "Del / Backspace",
        "",
        "Delete harness inventory",
        "Harness inventory active",
        "",
        "src/dev/inventory_harness.rs",
        "",
    ),
    (
        "Dev Mode",
        "Items — Harness",
        "A / U / O / V / H / M",
        "",
        "Add stack / unique / auto-sort / validate / split half / merge",
        "Harness inventory active",
        "",
        "src/dev/inventory_harness.rs",
        "",
    ),
    # --- WORLD TOOLS ---
    (
        "Dev Mode",
        "World Tools — Piles",
        "V",
        "",
        "Validate world inventory",
        "World Tools tab",
        "",
        "src/dev/pile_harness.rs",
        "",
    ),
    (
        "Dev Mode",
        "World Tools — Piles",
        "P / D / O / H / G / L",
        "",
        "Spawn pile / drop entry / drop one / half / pickup / loot",
        "World Tools; unit selected",
        "",
        "src/dev/pile_harness.rs",
        "",
    ),
    (
        "Dev Mode",
        "World Tools — Treasury",
        "J / B / C / Y / E",
        "",
        "Transaction log / wealth audit / create treasury / inspect / deposit",
        "World Tools; building selected (except J/B)",
        "",
        "src/dev/treasury_harness.rs",
        "",
    ),
]

HEADER = (
    "Category",
    "Subcategory",
    "Key / Input",
    "Modifiers",
    "Action",
    "Context / Preconditions",
    "Blocked When",
    "Source File",
    "Overlap Notes",
)

META_ROWS = [
    ("HOTKEY REGISTRY — Chasma", "", "", "", "", "", "", "", ""),
    (
        "Maintenance: update this sheet whenever keyboard bindings change in src/.",
        "",
        "",
        "",
        "Regenerate: python tools/update_hotkeys_sheet.py",
        "Audit code: rg 'KeyCode::' src/",
        "Also update docs/dev-mode.md if player-facing",
        "",
        "Last regenerated by tools/update_hotkeys_sheet.py",
    ),
    ("", "", "", "", "", "", "", "", ""),
]


def style_sheet(ws) -> None:
    header_fill = PatternFill("solid", fgColor="1F4E79")
    header_font = Font(color="FFFFFF", bold=True)
    meta_fill = PatternFill("solid", fgColor="D9E1F2")

    for col, title in enumerate(HEADER, start=1):
        cell = ws.cell(row=4, column=col, value=title)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

    for r, row in enumerate(META_ROWS, start=1):
        for c, val in enumerate(row, start=1):
            cell = ws.cell(row=r, column=c, value=val)
            cell.fill = meta_fill
            if r == 1 and c == 1:
                cell.font = Font(bold=True, size=14)

    widths = [14, 22, 16, 12, 42, 36, 24, 34, 36]
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w

    ws.freeze_panes = "A5"
    ws.auto_filter.ref = f"A4:{get_column_letter(len(HEADER))}{4 + len(ROWS)}"


def main() -> None:
    wb = openpyxl.load_workbook(WORKBOOK)
    if SHEET_NAME in wb.sheetnames:
        del wb[SHEET_NAME]
    ws = wb.create_sheet(SHEET_NAME)

    # Place after Development sheet if present
    if "Development" in wb.sheetnames:
        dev_idx = wb.sheetnames.index("Development")
        wb.move_sheet(ws, offset=dev_idx + 1 - len(wb.sheetnames))

    for r, row in enumerate(META_ROWS, start=1):
        for c, val in enumerate(row, start=1):
            ws.cell(row=r, column=c, value=val)

    for c, title in enumerate(HEADER, start=1):
        ws.cell(row=4, column=c, value=title)

    for r, row in enumerate(ROWS, start=5):
        for c, val in enumerate(row, start=1):
            cell = ws.cell(row=r, column=c, value=val)
            cell.alignment = Alignment(vertical="top", wrap_text=True)

    style_sheet(ws)
    wb.save(WORKBOOK)
    print(f"Wrote {len(ROWS)} hotkey rows to '{SHEET_NAME}' in {WORKBOOK}")


if __name__ == "__main__":
    main()
